<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>10</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>FtDSharp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Ai">
      <HintPath>../ftd-managed/Ai.dll</HintPath>
    </Reference>
    <Reference Include="Common">
      <HintPath>../ftd-managed/Common.dll</HintPath>
    </Reference>
    <Reference Include="Core">
      <HintPath>../ftd-managed/Core.dll</HintPath>
    </Reference>
    <Reference Include="Ftd">
      <HintPath>../ftd-managed/Ftd.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../ftd-managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>