<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FtDSharp.Release</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../FtDSharp.csproj" />
  </ItemGroup>

</Project>
